### ISSUE TITLE
'Could not create task ':iosTest'' error

### ISSUE THREAD

**Issue by tylerwilson** [AlecStrong/kotlin-native-cocoapods#21]
I am attempting to use this plugin to generate a fat framework for consumption in my iOS projects. When I add it according to the readme, I get the following stack trace. Any ideas? If needed, I can send my build.gradle separately (it is messy with lots of commented out blocks).

I am using IntelliJ IDEA Community Edition with Kotlin 1.3.31 plugin.

`Caused by: org.gradle.api.internal.AbstractMutationGuard$IllegalMutationException: Gradle#projectsEvaluated(Action) on build '<my>library' cannot be executed in the current context.
	at org.gradle.api.internal.AbstractMutationGuard.createIllegalStateException(AbstractMutationGuard.java:39)
	at org.gradle.api.internal.AbstractMutationGuard.assertMutationAllowed(AbstractMutationGuard.java:34)
	at org.gradle.invocation.DefaultGradle.assertProjectMutatingMethodAllowed(DefaultGradle.java:285)
	at org.gradle.invocation.DefaultGradle.projectsEvaluated(DefaultGradle.java:352)
	at org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeCompilationKt$registerDeprecatedApi$1$deprecatedAPIs$1.apply(KotlinNativeCompilation.kt:54)
	at org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeCompilationKt$registerDeprecatedApi$1$deprecatedAPIs$1.apply(KotlinNativeCompilation.kt)
	at org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeCompilationKt.registerDeprecatedApi(KotlinNativeCompilation.kt:53)
	at org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeCompilationKt.access$registerDeprecatedApi(KotlinNativeCompilation.kt:1)
	at org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeCompilation.findLinkTask(KotlinNativeCompilation.kt:212)
	at org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeCompilation.getLinkTask(KotlinNativeCompilation.kt:216)
	at com.alecstrong.cocoapods.gradle.plugin.CocoapodsTargetPreset$createTarget$1.execute(CocoapodsTargetPreset.kt:37)
	at com.alecstrong.cocoapods.gradle.plugin.CocoapodsTargetPreset$createTarget$1.execute(CocoapodsTargetPreset.kt:19)`

**Comment by jonasbark** [comment]
@AlecStrong I created a Pull Request to fix this. Although Jetbrains provides integrated cocoapods support I think this plugin should still be updated for compatibility reasons. Along with the fact that the fatFramework task does not support builds for Simulator (https://youtrack.jetbrains.com/issue/KT-31829)
